services:
  rentee:
    build: ./rentee-bot
    restart: on-failure:3
    depends_on: 
      db:
        condition: service_healthy
    env_file:
      - prod.env

  renter:
    build: ./renter-bot
    restart: on-failure:3
    depends_on: 
      db:
        condition: service_healthy
    env_file:
      - prod.env
    
  parser:
    build: ./parser
    depends_on: 
      db:
        condition: service_healthy
    env_file:
      - prod.env

  cache:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes: 
      - ./mongodb-data-prod:/data/db

  db:
    image: postgres
    restart: always
    env_file:
      - prod.env
    volumes:
      - ./db-data-prod/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5